apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attendance-checker-fe-prod-ingress
spec:
  $patch: replace
  tls:
    - hosts:
        - taghedge.scg.skku.ac.kr
      secretName: gitops-tls
  rules:
    - host: taghedge.scg.skku.ac.kr
      http:
        paths: 
          - path: /
            pathType: Prefix
            backend:
              service:
                name: attendance-checker-fe-prod-service
                port:
                  number: 80
