apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-fe-prod
resources:
- namespace.yaml
- ../../base/fe


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-fe-ingress
images:
- name: scgskku/attendance-checker-fe-prod
  newTag: 69c6510cb49c5c00b0bd7b13741cf676d547f3b9-31577048294-1
