apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-fe-prod
resources:
- namespace.yaml
- ../../base/fe


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-fe-prod-ingress
images:
- name: scgskku/attendance-checker-fe-prod
  newTag: e86211847c2ed004dcad29542dd466d108819f29-36329529139-1
