apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attendance-checker-be-ingress
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://attendance.scg.skku.ac.kr"
spec:
  $patch: replace
  tls:
    - hosts:
        - api.attendance.scg.skku.ac.kr
      secretName: gitops-tls
  rules:
    - host: api.attendance.scg.skku.ac.kr
      http:
        paths:
          - path: /v1/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: attendance-checker-be-prod-service
                port:
                  number: 80
