apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-be-prod
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-be-ingress
images:
- name: scgskku/attendance-checker-be-prod
  newTag: 95a1e45372460fa64374820bf6b000b8c22e2f58-31782763586-1
