apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-be-prod
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-be-prod-ingress
images:
- name: scgskku/attendance-checker-be-prod
  newTag: ee2cc30a5354cfd5af4d36ba17ddd72292f2a02a-37029576773-1
