apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attendance-checker-be-prod
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.yaml
  target:
    kind: Ingress
    name: attendance-checker-be-prod-ingress
images:
- name: scgskku/attendance-checker-be-prod
  newTag: 77d114d833875e425fb2326d9638cfb50d536947-35581350031-1
