apiVersion: v1
kind: Secret
metadata:
  name: attendance-checker-be-prod-secret
  annotations:
    avp.kubernetes.io/path: kv/data/attendance-checker-be-prod-secret
type: Opaque
stringData:
  DATABASE_URL: <path:kv/data/attendance-checker-be-dev-secret#DATABASE_URL>
  DATABASE_USERNAME: <path:kv/data/attendance-checker-be-dev-secret#DATABASE_USERNAME>
  DATABASE_PASSWORD: <path:kv/data/attendance-checker-be-dev-secret#DATABASE_PASSWORD>
  GOOGLE_OAUTH_CLIENT_ID: <path:kv/data/attendance-checker-be-dev-secret#GOOGLE_OAUTH_CLIENT_ID>
  GOOGLE_OAUTH_CLIENT_SECRET: <path:kv/data/attendance-checker-be-dev-secret#GOOGLE_OAUTH_CLIENT_SECRET>
  JWT_SECRET_KEY: <path:kv/data/attendance-checker-be-dev-secret#JWT_SECRET_KEY>
  MINIO_ACCESS_KEY: <path:kv/data/attendance-checker-be-dev-secret#MINIO_ACCESS_KEY>
  MINIO_BUCKET: <path:kv/data/attendance-checker-be-dev-secret#MINIO_BUCKET>
  MINIO_ENDPOINT: <path:kv/data/attendance-checker-be-dev-secret#MINIO_ENDPOINT>
  MINIO_SECRET_KEY: <path:kv/data/attendance-checker-be-dev-secret#MINIO_SECRET_KEY>
